environment: production
chdir: /var/www/wwqi-search/current/
address: 127.0.0.1
user: ubuntu
group: ubuntu
port: 8000
pid: /var/pids/wwqi-search/thin.pid
rackup: /var/www/wwqi-search/current/config.ru
log: /var/logs/wwqi-search.log
max_conns: 1024
timeout: 30
max_persistent_conns: 256
daemonize: true
